POST https://node-zero-4igq.onrender.com/videos
Content-Type: application/json

{
    "title": "Video #4",
    "description": "Que bacana",
    "duration": 108
}

###

GET  https://node-zero-4igq.onrender.com/videos

###
GET  https://node-zero-4igq.onrender.com/videos?search=node

###

PUT https://node-zero-4igq.onrender.com/videos/16775c2c-552e-4807-9571-d311323d989f
Content-Type: application/json

{
    "title": "Video #2",
    "description": "Primeira API",
    "duration": 108
}

###

DELETE  https://node-zero-4igq.onrender.com/videos/866a333a-7695-4048-94c4-01f052cb6cdd